### ISSUE TITLE
wallet address counter diff by one between 2 explorers

### ISSUE THREAD

**Issue by taokayan** [VaultaFoundation/blockscout#1]
the number of wallet addresses always diff by 1 between https://explorer-testnet.trust.one/ and https://explorer2-testnet.trust.one/

versions:
```
commit a55279f9372f893eb1bf509ecbd67ac5aef229a7 (HEAD -> trust, origin/trust)
Author: Matias Romeo <matias.romeo@gmail.com>
Date:   Wed Nov 23 04:01:02 2022 -0300

    trust env
```

**Comment by yarkinwho** [comment]
The number is get from SELECT reltuples FROM pg_class WHERE relname = 'addresses';
Then we can have the following points:
1 it's from pg_class so it's a fast estimation and not meant to be accurate. 
2 It's proper to get the info from pg_class as we value performance more than accuracy in this case
3 there's little we can do here. (an ANALYZE may fix the issue but it can be diff again next minute)

So my suggestion is as long as the estimated number is within reasonable range, we can ignore this issue safely.

**Comment by taokayan** [comment]
agree with @yarkinwho , we should ignore this for now as long as the diff is within a reasonable small range.
