### ISSUE TITLE
5xx page issues

### ISSUE THREAD

**Issue by Joshua2Mars** [VaultaFoundation/blockscout#13]
https://docs.google.com/document/d/1zA33Ik3c-1Hq-MyxZCGbxAqN4Hu-5G8EH7G-QTQtG7s/edit
https://docs.google.com/document/d/1sQTk6zcENzoDQBdnykObYj4GPuaWvpaZ1Upoq9wNqxs/edit#heading=h.tgwa4puicwmp

Issue details
URLs that return one of the 5xx HTTP status codes (Server Error).
URLs return 5xx status codes when the server is not able to fulfill the request.
These URLs can be accessed neither by your website visitors nor by the search engines crawlers. Crawlers will be forced to abandon the request while people will most likely leave your website.

How to fix
Review the list of 5xx URLs.
Try to reproduce the server error reported by the Site Audit for these URLs in your browser. You should also check the error logs for your server. If this is an ongoing problem and a lot of internal pages return 5xx code, you need to check with your hosting provider or with your web developers. Your server may be overloaded or misconfigured.
You should also note that this can be a temporary issue, e.g. when the crawl took place during some maintenance on your website's server.
Learn more: https://help.ahrefs.com/en/articles/2453036-what-does-5xx-page-error-mean-in-site-audit

**Comment by yarkinwho** [comment]
Close the issue as we need more information.

Feel free to reopen it when there are updates.
