### ISSUE TITLE
Robots.txt not accessible

### ISSUE THREAD

**Issue by Joshua2Mars** [VaultaFoundation/blockscout#14]
https://docs.google.com/document/d/10jfPxoQ1_DmHve30DWBRN9_9C2u-AZKCW7Agp13FCHQ/edit#heading=h.ig0cyzhv1ysb

Issue details
Site Audit bot could not access the robots.txt file on your website. We either got an HTTP code that denies us access to the file, or the server failed to satisfy the request. When this happens, our bot behaves conservatively, and considers the entire domain disallowed from crawling.
The most likely reason is that your website is blocking our crawler from accessing it on the server side. This issue should not affect visitors, but it does mean that some crawlers may not be able to crawl your website.
How to fix
Check that you do not have a firewall or plugin blocking bots; and if you do, to whitelist our AhrefsSiteAudit user-agent on that system.
Please also add [our IPs](https://help.ahrefs.com/about-ahrefs/what-is-the-list-of-your-current-ip-ranges) to the server's whitelist.

**Comment by yarkinwho** [comment]
https://explorer.evm.eosnetwork.com/robots.txt 
https://explorer.testnet.evm.eosnetwork.com/robots.txt

it's there. 

Are you sure you want Robots.txt?

**Comment by yarkinwho** [comment]
Close the issue as we need more information.

Feel free to reopen it when there are updates.
