### ISSUE TITLE
Unable to verify contract due to contract creation transaction not being indexed yet

### ISSUE THREAD

**Issue by nsjames** [VaultaFoundation/blockscout#20]
A user report came in which shows that in the case of a contract not being indexed yet, they are unable to verify their contract. 
However, it seems the contract creation transaction does show up on the stack. 

The address also says: "Error: Could not determine contract creator." on blockscout.

### Environment

* Mainnet

### Steps to reproduce

Please see the internal EVM telegram group as the reporter has not approved public display of their information.

### Expected behaviour

The contract should be able to be verified.

### Actual behaviour

The contract cannot be verified.

**Comment by yarkinwho** [comment]
It's actually caused by https://github.com/eosnetworkfoundation/eos-evm/issues/551
