### ISSUE TITLE
Indexer seems constantly accessing some IPFS address

### ISSUE THREAD

**Issue by yarkinwho** [VaultaFoundation/blockscout#24]
some millions of access per day.

This looks not anticipated behavior.

**Comment by yarkinwho** [comment]
Trying to turn off token instance fetcher to see the effect.

**Comment by yarkinwho** [comment]
Even if this fixed issue, we should find a time setting up a separate sandbox environment to reproduce and fix the issue from root cause.

**Comment by stephenpdiesel** [comment]
No recent feedback on this task, so closing
