### ISSUE TITLE
Test updating to latest version of explorer

### ISSUE THREAD

**Issue by stephenpdiesel** [VaultaFoundation/blockscout#33]
The blockscout team suggested that they have resolved the CPU issue. We should upgrade to the latest version to verify this has been fixed.

**Comment by yarkinwho** [comment]
Tested and the memory/cpu consumption is still slowly going up, albeit slower maybe.

So upgrading to v6.0.0 will not change too much.

We will not upgrade until we want to shift to the new frontend.
